// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://trzrictfwfsmlpkbazqi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRyenJpY3Rmd2ZzbWxwa2JhenFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAzMjU2NTgsImV4cCI6MjA4NTkwMTY1OH0.TrYrrsJk1CZiq4PaQOvf_FcDnpfKei8qxVsXEUGuTHM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});